 <?php if(!empty($flash)) { 
  foreach($flash as $message) {
    print_r($message);
  } } ?>
<form action="/users/<?= htmlspecialchars($id) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
      <label for="user-nickname">
          Nickname
          <input type="text" id="user-nickname" name="user[nickname]" value="<?= htmlspecialchars($user['nickname'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['nickname'])): ?>
          <div><?= $errors['nickname'] ?></div>
      <?php endif ?>
    </div>
    <div>
      <label for="user-email">
          Email
          <input type="email" id="user-email" name="user[email]" value="<?= htmlspecialchars($user['email'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['email'])): ?>
          <div><?= $errors['email'] ?></div>
      <?php endif ?>
    </div>
    <input type="submit" value="Update">
</form>
<form action="/users/<?= $id ?>" method="post">
  <input type="hidden" name="_METHOD" value="DELETE">
  <input type="submit" value="Remove">
</form>
<p><a href="/users">Back to the users list</a></p>
