<h1>Add New User</h1>
<form action="/users" method="POST">
  <div>
    <label for="add-nickname">
        Nickname
      <input type="text" id="add-nickname" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?? '' ?>">
    </label>
    <?php if (isset($errors['nickname'])): ?>
      <div><?= $errors['nickname'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label for="add-email">
        Email
      <input type="email" id="add-email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?? '' ?>">
    </label>
    <?php if (isset($errors['email'])): ?>
      <div><?= $errors['email'] ?></div>
    <?php endif ?>
  </div>
  <input type="submit" value="Sign Up">
</form>
